### ISSUE TITLE
Internal properties throw a core error

### ISSUE THREAD

**Issue by codeth** [open-wc/custom-elements-manifest#195] opened 2023-01-09 12:22 UTC
# Playground issue

Reproduction URL: 
https://custom-elements-manifest.netlify.app/?source=CmltcG9ydCB7IExpdEVsZW1lbnQsIGNzcyB9IGZyb20gJ2xpdCc7CmltcG9ydCB7IHByb3BlcnR5IH0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnCgpleHBvcnQgY2xhc3MgTXlFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7CiAgc3RhdGljIHN0eWxlcyA9IGNzc2AKICAgIDpob3N0KFtmbGFnZ2VkXSkgewogICAgICBjb2xvcjogcmVkOwogICAgfQogIGA7CgogIC8qKgogICAqIFNvbWUgZGVzY3JpcHRpb24KICAgKi8KICBAcHJvcGVydHkoKQogIGZvbyA9ICdoZWxsbyc7CgogIC8qKgogICAqIEEgcHJvcGVydHkgc2V0IGludGVybmFsbHkgdGhhdCByZWZsZWN0cyB1cCB0byBhbiBhdHRyaWJ1dGUgdGhhdCBpcyBvbmx5IHVzZWQgZm9yIHN0eWxpbmcsIHNvIGlzIG1hcmtlZCBhcyBpbnRlcm5hbAogICAqIAogICAqIEBpbnRlcm5hbAogICAqLwogIEBwcm9wZXJ0eSh7IHR5cGU6IEJvb2xlYW4sIHJlZmxlY3Q6IHRydWUgfSkKICBwcml2YXRlIGZsYWdnZWQgPSBmYWxzZTsKCiAgbXlNZXRob2QoKXt9Cn0K&library=litelement

## Additional information:
The repro example shows a property marked as `@internal` with JSDoc. It is used to set an internal state we want to reflect up to an attribute so it can be used for styling. Whilst this does mean it is still available on the component's public API, we want to exclude it from the generated docs, but that is throwing the error.

**Comment by thepassle** [comment] 2023-01-09 12:39
duplicate of https://github.com/open-wc/custom-elements-manifest/issues/194

**Closed by thepassle** 2023-01-09 12:39 UTC

**Comment by codeth** [comment] 2023-01-09 12:41
Ah! Apologies, I blindly followed through from the CLI output and forgot to search for existing issues first.

**Comment by thepassle** [comment] 2023-01-09 12:54
No worries :)
