### ISSUE TITLE
CEM fails with `@link` `@attr` and `@internal`

### ISSUE THREAD

**Issue by matteematt** [open-wc/custom-elements-manifest#208] opened 2023-05-10 14:49 UTC
**Checklist**
- [X] Did you run the analyzer with the `--dev` flag to get more information?
- [ ] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)? - I have an example of the failures in my repo here https://github.com/matteematt/cem-tsdoc-param-link-issue/commit/24b3ed8d5e927fd48ef853153fc9c152391f96d4

Completing the items above will greatly improve triaging time of your issue.

**Expected behavior**

Should parse the inputs and produce an output. Instead I am getting a runtime error

**Comment by thepassle** [comment] 2023-05-10 15:02
Im unable to reproduce: https://custom-elements-manifest.netlify.app/?source=CmNsYXNzIE15RWxlbWVudCBleHRlbmRzIEhUTUxFbGVtZW50IHsKICAgIC8qKgogICAgICogZm9vIHtAbGluayBVc2Vycy5lbnRpdHlDb2x1bW59IGJhcgogICAgICogQGludGVybmFsCiAgICAgKi8KICAgIEBhdHRyIGZvbyA9ICcnOwp9CgpjdXN0b21FbGVtZW50cy5kZWZpbmUoJ215LWVsZW1lbnQnLCBNeUVsZW1lbnQpOwo%3D&library=null

Can you provide a reproduction in the playground please

**Comment by thepassle** [comment] 2023-05-10 15:10
fixed in `0.8.2`

**Closed** 2023-05-10 15:10 UTC
